# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-04-05 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Two', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_title', models.CharField(max_length=32)),
                ('b_content', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='p_name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
